global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'bike-inventory-api'
    static_configs:
      - targets: ['app:3000']
        labels:
          app: 'bike-inventory-api'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']